language: node_js
node_js:
  - 12.14.0
cache:
  directories:
  - node_modules
before_install:
  - sudo apt-get update
  - sudo apt-get -y install ruby openjdk-8-jre graphviz
  - sudo gem install asciidoctor asciidoctor-diagram
script:
  - CI=false npm run deploy
